# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):
    tmpdir = 'UNIT_TESTS_TMPDIR="%s"' % bld.bldnode.make_node('tmp-files')
    bld.program(
        target=f'{top}/unit-tests',
        name='unit-tests',
        source=bld.path.ant_glob(['*.cpp', 'unit-tests/**/*.cpp']),
        use='libndn-cert',
        defines=[tmpdir],
        includes=top,
        install_path=None)
