# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):

    bld(features='cxx cxxprogram',
        target='../bin/ndncert-client',
        source='ndncert-client.cpp',
        use='ndn-cert')

    bld(features='cxx cxxprogram',
        target='../bin/ndncert-ca-server',
        source='ndncert-ca-server.cpp',
        use='ndn-cert')
