# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):
    bld.program(
        name='ndncert-client',
        target=f'{top}/bin/ndncert-client',
        source='ndncert-client.cpp',
        use='BOOST_TOOLS libndn-cert')

    bld.program(
        name='ndncert-ca-server',
        target=f'{top}/bin/ndncert-ca-server',
        source='ndncert-ca-server.cpp',
        use='BOOST_TOOLS libndn-cert')

    bld.program(
        name='ndncert-ca-status',
        target=f'{top}/bin/ndncert-ca-status',
        source='ndncert-ca-status.cpp',
        use='BOOST_TOOLS libndn-cert')

    bld.program(
        name='ndncert-dns-client',
        target=f'{top}/bin/ndncert-dns-client',
        source='ndncert-dns-client.cpp',
        use='BOOST_TOOLS libndn-cert')
